server:
  port: 8090
spring:
  application:
    name: hr-payroll
hr-worker:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:8000,http://localhost:8001