server:
  port: ${PORT:0}
spring:
  # spring config client config
  profiles:
    active: test
  config:
    import: 'optional:configserver:http://localhost:8888'
  application:
    name: hr-worker
  jpa:
    defer-datasource-initialization: true
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

