server:
  port: 8090

spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    ddl:auto: create-drop
  datasource:
      url: jdbc:h2:mem:testdb
      username: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console