server:
  port: ${PORT:0}
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: hr-oauth
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
oauth:
  service-registry:
    provides-uri: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    jks:
      keypass: 123456
      storepass: 123456
      alias: hr-oauth
      path: keystore/hr-oauth.jks