server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RossyFranca/ms-config-server
    server:
      git:
        default-label: main
  application:
    name: hr-config-server
