server:
  port: 8765
spring:
  application:
    name: hr-spring-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/workers/**
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/payments/**
        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/users/**
        - id: hr-oauth
          uri: lb://hr-oauth
          predicates:
            - Path=/oauth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


